import localFont from "next/font/local";
import "./globals.css";
import { FaShoppingCart, FaSearch } from "react-icons/fa";
import { FaUserPlus, FaUser } from "react-icons/fa";
import Image from "next/image";
import Logo from "../public/logo.png";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "E-Commerce BD",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <nav className="bg-gray-800 text-white p-4">
          <div className="container mx-auto flex items-center justify-between ">

            {/* Logo Start */}
            <div className="w-[10%] flex justify-center">
              <Image width="60" height="60" src={Logo} alt="Logo" className="cursor-pointer " />
            </div>
            {/* Logo End */}

            {/* Search Box Start */}
            <div className="w-[70%] mx-4">             
            <form className="max-w-md mx-auto">   
                <label htmlFor="default-search" className="mb-2 text-sm font-medium text-gray-900 sr-only dark:text-white">Search</label>
                <div className="relative">
                    <div className="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none fo">
                        <FaSearch className="w-4 h-4 text-gray-500 dark:text-gray-400" />
                    </div>
                    <input 
                      type="search" 
                      id="default-search" 
                      className="block w-full p-4 ps-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 outline-none" 
                      placeholder="Search your Product" 
                      required 
                    />
                    <button 
                      type="submit" 
                      className="text-white absolute end-2.5 bottom-2.5 bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
                    >
                      Search
                    </button>
                </div>
              </form> 
            </div>
            {/* Search Box End */}

            {/* User Icons Start */}
            <ul className=" w-[15%] flex gap-x-8 items-center justify-end  !important">
              {/* Cart Icon */}
              <li className="relative">
                <a href="/cart" className="flex items-center">
                  <FaShoppingCart className="text-3xl" />
                  <span className="absolute top-0 right-0 bg-red-500 text-white text-xs rounded-full px-1">0</span>
                </a>
              </li>
             
              <li className="flex items-center border p-3 rounded-md">
                <a href="/signin" className="flex items-center">
                  <FaUser className="text-2xl" />
                  <span className="ml-1">Sign In</span>
                </a>
              </li>
            </ul>
            {/* User Icons End */}
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
